### ISSUE TITLE
Add config for default type in Icon component

### ISSUE THREAD

**Issue by jotaviobiondo** [miguel-s/ex_heroicons#5]
Hi! Nice work, great lib :) 

Right now the `type` prop of `Icon` component is required, but it will be nice to have a global config to set this prop.

Example: 

```elixir
config :ex_heroicons, default_icon_type: "outline"
```

And then use it like this:

```html
<Heroicons.Components.Icon name="academic-cap" />
```

**Comment by miguel-s** [comment]
Thanks @jotaviobiondo!

I agree that being able to set a default type would add some convenience to the component, will look into it 👍
