### ISSUE TITLE
IO.inspect in live_view Module

### ISSUE THREAD

**Issue by Francisco-Castro** [miguel-s/ex_heroicons#7]
I guess the following inspect should be deleted or at least commented:

https://github.com/miguel-s/ex_heroicons/blob/7edb691032dbf2350e96dfc1b49582fe91ed79c9/lib/heroicons/live_view.ex#L33

What do you think?

**Comment by miguel-s** [comment]
That's embarrassing 😅 Thanks for raising the issue!

I removed the `IO.inspect` and released version 0.4.1
